In [20]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
import os
from keras.utils import to_categorical


#os.chdir('/Users/akashsrivastava/Desktop/MachineLearning/kaggle/iris-keras')

dataset = pd.read_csv('/home/kamal/ML/Datasets/Iris.csv')


In [28]:
#Splitting the data into training and test test
X = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5].values
# print (y)
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
# print (y1)
Y = pd.get_dummies(y1).values
# print (Y)

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 


In [29]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(10,input_shape=(4,),activation='tanh'))
model.add(Dense(8,activation='tanh'))
model.add(Dense(6,activation='tanh'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(X_train,y_train,epochs=100)
# print (X_test)
y_pred = model.predict(X_test)
# print (y_pred)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)
# print (y_pred_class)
from sklearn.metrics import accuracy_score
accuracy_score(y_test_class,y_pred_class)

Epoch 1/100
120/120 [==============================] - 0s 120us/step - loss: 0.0543 - acc: 0.9750
Epoch 2/100
120/120 [==============================] - 0s 64us/step - loss: 0.0513 - acc: 0.9833
Epoch 3/100
120/120 [==============================] - 0s 92us/step - loss: 0.0768 - acc: 0.9667
Epoch 4/100
120/120 [==============================] - 0s 70us/step - loss: 0.0731 - acc: 0.9750
Epoch 5/100
120/120 [==============================] - 0s 79us/step - loss: 0.1092 - acc: 0.9500
Epoch 6/100
120/120 [==============================] - 0s 99us/step - loss: 0.1072 - acc: 0.9500
Epoch 7/100
120/120 [==============================] - 0s 73us/step - loss: 0.0705 - acc: 0.9750
Epoch 8/100
120/120 [==============================] - 0s 96us/step - loss: 0.0710 - acc: 0.9667
Epoch 9/100
120/120 [==============================] - 0s 78us/step - loss: 0.0662 - acc: 0.9750
Epoch 10/100
120/120 [==============================] - 0s 73us/step - loss: 0.0590 - acc: 0.9833
Epoch 11/100
120/120 [======

120/120 [==============================] - 0s 106us/step - loss: 0.0510 - acc: 0.9833
Epoch 85/100
120/120 [==============================] - 0s 107us/step - loss: 0.0547 - acc: 0.9833
Epoch 86/100
120/120 [==============================] - 0s 83us/step - loss: 0.0523 - acc: 0.9750
Epoch 87/100
120/120 [==============================] - 0s 139us/step - loss: 0.0534 - acc: 0.9750
Epoch 88/100
120/120 [==============================] - 0s 98us/step - loss: 0.0740 - acc: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 123us/step - loss: 0.0954 - acc: 0.9667
Epoch 90/100
120/120 [==============================] - 0s 92us/step - loss: 0.1435 - acc: 0.9417
Epoch 91/100
120/120 [==============================] - 0s 68us/step - loss: 0.1736 - acc: 0.8833
Epoch 92/100
120/120 [==============================] - 0s 103us/step - loss: 0.1017 - acc: 0.9583
Epoch 93/100
120/120 [==============================] - 0s 66us/step - loss: 0.1075 - acc: 0.9500
Epoch 94/100
120/120 [======

1.0

In [31]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))



             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [42]:
a=np.array([[3.8,2,4,0.5],[2,2,2,3]])
print (a)
pred = model.predict(a)
print (pred)
y_test_class = np.argmax(y_test,axis=1)
y_pred = np.argmax(pred,axis=1)
print (y_pred)

[[3.8 2.  4.  0.5]
 [2.  2.  2.  3. ]]
[[3.5980778e-05 9.9919456e-01 7.6944963e-04]
 [3.7473848e-05 1.6961070e-03 9.9826640e-01]]
[1 2]
